//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDDCORDICARRITOEntities3 : DbContext
    {
        public BDDCORDICARRITOEntities3()
            : base("name=BDDCORDICARRITOEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_CATEGORIA> TBL_CATEGORIA { get; set; }
        public virtual DbSet<TBL_CLIENTE> TBL_CLIENTE { get; set; }
        public virtual DbSet<TBL_DETALLEIMPUESTOS> TBL_DETALLEIMPUESTOS { get; set; }
        public virtual DbSet<TBL_DETALLEPEDIDO> TBL_DETALLEPEDIDO { get; set; }
        public virtual DbSet<TBL_DIRECCIONES> TBL_DIRECCIONES { get; set; }
        public virtual DbSet<TBL_FORMAPAGO> TBL_FORMAPAGO { get; set; }
        public virtual DbSet<TBL_IMPUESTOS> TBL_IMPUESTOS { get; set; }
        public virtual DbSet<TBL_PAGOS> TBL_PAGOS { get; set; }
        public virtual DbSet<TBL_PEDIDO> TBL_PEDIDO { get; set; }
        public virtual DbSet<TBL_PRODUCTO> TBL_PRODUCTO { get; set; }
        public virtual DbSet<TBL_ROL> TBL_ROL { get; set; }
        public virtual DbSet<TBL_USUARIO> TBL_USUARIO { get; set; }
    }
}
