//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FORMAPAGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_FORMAPAGO()
        {
            this.TBL_PAGOS = new HashSet<TBL_PAGOS>();
        }
    
        public byte fpa_id { get; set; }
        public string fpa_descripcion { get; set; }
        public string fpa_codigosri { get; set; }
        public System.DateTime fpa_fechacreacion { get; set; }
        public string fpa_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PAGOS> TBL_PAGOS { get; set; }
    }
}
