//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CLIENTE()
        {
            this.TBL_DIRECCIONES = new HashSet<TBL_DIRECCIONES>();
            this.TBL_PEDIDO = new HashSet<TBL_PEDIDO>();
        }
    
        public long cli_id { get; set; }
        public string cli_identificacion { get; set; }
        public string cli_tipoidentificacion { get; set; }
        public string cli_apellidos { get; set; }
        public string cli_nombres { get; set; }
        public string cli_genero { get; set; }
        public System.DateTime cli_fechanacimiento { get; set; }
        public string cli_telefono { get; set; }
        public string cli_celular { get; set; }
        public string cli_email { get; set; }
        public System.DateTime cli_fechacreacion { get; set; }
        public string cli_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DIRECCIONES> TBL_DIRECCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PEDIDO> TBL_PEDIDO { get; set; }
    }
}
