//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIO
    {
        public int usu_id { get; set; }
        public string usu_correo { get; set; }
        public string usu_password { get; set; }
        public string usu_apellidos { get; set; }
        public string usu_nombres { get; set; }
        public string usu_status { get; set; }
        public System.DateTime usu_add { get; set; }
        public Nullable<byte> rol_id { get; set; }
    
        public virtual TBL_ROL TBL_ROL { get; set; }
    }
}
