//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DIRECCIONES
    {
        public int dir_id { get; set; }
        public string dir_principal { get; set; }
        public string dir_secundaria { get; set; }
        public string dir_numeracion { get; set; }
        public string dir_referencia { get; set; }
        public string dir_codidopostal { get; set; }
        public System.DateTime dir_fechacreacion { get; set; }
        public string dir_status { get; set; }
        public Nullable<long> cli_id { get; set; }
    
        public virtual TBL_CLIENTE TBL_CLIENTE { get; set; }
    }
}
