//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLEIMPUESTO
    {
        public int DIM_ID { get; set; }
        public Nullable<int> DEP_CODIGO { get; set; }
        public int IMP_ID { get; set; }
        public decimal DIM_VALOR { get; set; }
        public string DIM_STATUS { get; set; }
        public System.DateTime DIM_FECHACREACION { get; set; }
    }
}
