//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DIRECCIONES
    {
        public int DIR_ID { get; set; }
        public string DIR_PRINCIPAL { get; set; }
        public string DIR_SECUNDARIA { get; set; }
        public string DIR_NUMERACION { get; set; }
        public string DIR_REFERENCIA { get; set; }
        public string DIR_CODIGOPOSTAL { get; set; }
        public string DIR_STATUS { get; set; }
        public System.DateTime DIR_FECHACREACION { get; set; }
        public Nullable<long> CLI_ID { get; set; }
        public string CLI_IDENTIFICACION { get; set; }
    }
}
