//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CLIENTE
    {
        public long CLI_ID { get; set; }
        public string CLI_IDENTIFICACION { get; set; }
        public string CLI_TIPOIDENTIFICACION { get; set; }
        public string CLI_APELLIDOS { get; set; }
        public string CLI_NOMBRES { get; set; }
        public string CLI_GENERO { get; set; }
        public System.DateTime CLI_FECHANACIMIENTO { get; set; }
        public string CLI_TELEFONO { get; set; }
        public string CLI_CELULAR { get; set; }
        public string CLI_EMAIL { get; set; }
        public string CLI_STATUS { get; set; }
        public System.DateTime CLI_FECHACREACION { get; set; }
    }
}
