//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PEDIDO()
        {
            this.TBL_DETALLEPEDIDO = new HashSet<TBL_DETALLEPEDIDO>();
            this.TBL_PAGOS = new HashSet<TBL_PAGOS>();
        }
    
        public int ped_id { get; set; }
        public System.DateTime ped_fecha { get; set; }
        public int ped_numero { get; set; }
        public string ped_identificacion { get; set; }
        public string ped_cliente { get; set; }
        public string ped_direccion { get; set; }
        public string ped_telefono { get; set; }
        public decimal ped_subtotal { get; set; }
        public decimal ped_total { get; set; }
        public System.DateTime ped_fechacreacion { get; set; }
        public string ped_status { get; set; }
        public Nullable<long> cli_id { get; set; }
    
        public virtual TBL_CLIENTE TBL_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DETALLEPEDIDO> TBL_DETALLEPEDIDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PAGOS> TBL_PAGOS { get; set; }
    }
}
