//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_IMPUESTOS
    {
        public int IMP_ID { get; set; }
        public string IMP_CODIGOSRI { get; set; }
        public string IMP_DESCRIPCION { get; set; }
        public decimal IMP_PORCENTAJE { get; set; }
        public string IMP_STATUS { get; set; }
        public System.DateTime IMP_FECHACREACION { get; set; }
    }
}
