//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PAGOS
    {
        public int PAG_ID { get; set; }
        public System.DateTime PAG_FECHA { get; set; }
        public decimal PAG_VALOR { get; set; }
        public string PAG_STATUS { get; set; }
        public System.DateTime PAG_FECHACREACION { get; set; }
        public Nullable<int> PED_ID { get; set; }
        public Nullable<System.DateTime> PED_FECHA { get; set; }
        public int FPA_ID { get; set; }
    }
}
