//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLEPEDIDO
    {
        public int DEP_CODIGO { get; set; }
        public int DEP_CANTIDAD { get; set; }
        public string DEP_DESCRIPCION { get; set; }
        public decimal DEP_PRECIOUNITARIO { get; set; }
        public decimal DEP_PRECIOTOTAL { get; set; }
        public string DEP_STATUS { get; set; }
        public Nullable<int> PRO_ID { get; set; }
        public Nullable<int> PED_ID { get; set; }
        public Nullable<System.DateTime> PED_FECHA { get; set; }
    }
}
