//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PAGOS
    {
        public int pag_id { get; set; }
        public System.DateTime pag_fecha { get; set; }
        public decimal pag_valor { get; set; }
        public System.DateTime pag_fechacreacion { get; set; }
        public string pag_status { get; set; }
        public Nullable<int> ped_id { get; set; }
        public Nullable<byte> fpa_id { get; set; }
    
        public virtual TBL_FORMAPAGO TBL_FORMAPAGO { get; set; }
        public virtual TBL_PEDIDO TBL_PEDIDO { get; set; }
    }
}
