//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FORMAPAGO
    {
        public int FPA_ID { get; set; }
        public string FPA_DESCRIPCION { get; set; }
        public string FPA_CODIGOSRI { get; set; }
        public string FPA_STATUS { get; set; }
        public System.DateTime FPA_FECHACREACION { get; set; }
    }
}
