//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTO
    {
        public int PRO_ID { get; set; }
        public string PRO_CODIGO { get; set; }
        public string PRO_NOMBRE { get; set; }
        public decimal PRO_PRECIOCOMPRA { get; set; }
        public decimal PRO_PRECIOVENTA { get; set; }
        public string PRO_IMAGEN { get; set; }
        public string PRO_DESCRIPCION { get; set; }
        public int PRO_STOCKMINIMO { get; set; }
        public int PRO_STOCKMAXIMO { get; set; }
        public string PRO_STATUS { get; set; }
        public System.DateTime PRO_FECHACREACION { get; set; }
        public Nullable<short> CAT_ID { get; set; }
    }
}
