//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIO
    {
        public int USU_ID { get; set; }
        public string USU_CORREO { get; set; }
        public string USU_PASSWORD { get; set; }
        public string USU_APELLIDOS { get; set; }
        public string USU_NOMBRES { get; set; }
        public string USU_STATUS { get; set; }
        public System.DateTime USU_ADD { get; set; }
        public int ROL_ID { get; set; }
    }
}
