//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CATEGORIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CATEGORIA()
        {
            this.TBL_PRODUCTO = new HashSet<TBL_PRODUCTO>();
        }
    
        public short cat_id { get; set; }
        public string cat_nombre { get; set; }
        public string cat_descripcion { get; set; }
        public System.DateTime cat_fechacreacion { get; set; }
        public string cat_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PRODUCTO> TBL_PRODUCTO { get; set; }
    }
}
