//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ROL
    {
        public int ROL_ID { get; set; }
        public string ROL_DESCRIPCION { get; set; }
        public string ROL_STATUS { get; set; }
        public System.DateTime ROL_ADD { get; set; }
    }
}
