//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PEDIDO
    {
        public int PED_ID { get; set; }
        public System.DateTime PED_FECHA { get; set; }
        public int PED_NUMERO { get; set; }
        public string PED_IDENTIFICACION { get; set; }
        public string PED_CLIENTE { get; set; }
        public string PED_DIRECCION { get; set; }
        public string PED_TELEFONO { get; set; }
        public decimal PED_SUBTOTAL { get; set; }
        public decimal PED_TOTAL { get; set; }
        public string PED_STATUS { get; set; }
        public System.DateTime PED_FECHACREACION { get; set; }
        public Nullable<long> CLI_ID { get; set; }
        public string CLI_IDENTIFICACION { get; set; }
    }
}
